<a href="https://colab.research.google.com/github/gudiya-archi/Data-science/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# np.sort
import numpy as np
a = np.random.randint(1,100,15)
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[22, 24, 70, 17],
       [92, 23, 42,  3],
       [10, 81,  1, 19],
       [11, 91,  1, 11],
       [78, 24,  4, 33],
       [71, 51, 34, 50]])

In [ ]:
np.sort(a)

array([ 8,  8, 21, 27, 49, 51, 52, 56, 77, 81, 86, 88, 95, 98, 99])

In [ ]:
np.sort(b,axis=0)

array([[10, 23,  1,  3],
       [11, 24,  1, 11],
       [22, 24,  4, 17],
       [71, 51, 34, 19],
       [78, 81, 42, 33],
       [92, 91, 70, 50]])

In [ ]:
np.sort(b,axis=1)

array([[20, 43, 51, 92],
       [ 2, 30, 42, 68],
       [13, 26, 38, 39],
       [10, 35, 65, 67],
       [19, 61, 67, 85],
       [ 1, 32, 59, 86]])

In [ ]:
np.sort(a)[::-1]

array([99, 98, 95, 88, 86, 81, 77, 56, 52, 51, 49, 27, 21,  8,  8])

In [ ]:
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
# append code
np.append(a,200)

array([ 56,  86,  81,  99,  21,  88,  51,   8,  95,  52,  77,  49,  27,
        98,   8, 200])

In [ ]:
b

array([[22, 24, 70, 17],
       [92, 23, 42,  3],
       [10, 81,  1, 19],
       [11, 91,  1, 11],
       [78, 24,  4, 33],
       [71, 51, 34, 50]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)
# axis=1 is used for column

array([[22., 24., 70., 17.,  1.],
       [92., 23., 42.,  3.,  1.],
       [10., 81.,  1., 19.,  1.],
       [11., 91.,  1., 11.,  1.],
       [78., 24.,  4., 33.,  1.],
       [71., 51., 34., 50.,  1.]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)


array([[2.20000000e+01, 2.40000000e+01, 7.00000000e+01, 1.70000000e+01,
        2.47379445e-02],
       [9.20000000e+01, 2.30000000e+01, 4.20000000e+01, 3.00000000e+00,
        6.09307097e-03],
       [1.00000000e+01, 8.10000000e+01, 1.00000000e+00, 1.90000000e+01,
        8.30380761e-01],
       [1.10000000e+01, 9.10000000e+01, 1.00000000e+00, 1.10000000e+01,
        7.22462678e-01],
       [7.80000000e+01, 2.40000000e+01, 4.00000000e+00, 3.30000000e+01,
        5.84506605e-01],
       [7.10000000e+01, 5.10000000e+01, 3.40000000e+01, 5.00000000e+01,
        2.79133407e-01]])

In [ ]:
# np.concatenate
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# np.unique

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6,])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# np.expand_dims
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [ ]:
np.expand_dims(a,axis=1)

array([[56],
       [86],
       [81],
       [99],
       [21],
       [88],
       [51],
       [ 8],
       [95],
       [52],
       [77],
       [49],
       [27],
       [98],
       [ 8]])

In [ ]:
np.expand_dims(a,axis=0)



array([[56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8]])

In [ ]:
# np.where
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  3,  5,  6,  8,  9, 10, 13]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)
# np.where(condition,true,false)

array([ 0,  0,  0,  0, 21,  0,  0,  8,  0,  0,  0, 49, 27,  0,  8])

In [ ]:
np.where(a%2==0,0,a)

array([ 0,  0, 81, 99, 21,  0, 51,  0, 95,  0, 77, 49, 27,  0,  0])

In [ ]:
# argmax
# largest value of indices
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
np.argmax(a)

np.int64(3)

In [ ]:
b

array([[22, 24, 70, 17],
       [92, 23, 42,  3],
       [10, 81,  1, 19],
       [11, 91,  1, 11],
       [78, 24,  4, 33],
       [71, 51, 34, 50]])

In [ ]:
np.argmax(b,axis=0)

array([1, 3, 0, 5])

In [ ]:
np.argmax(b,axis=1)

array([2, 0, 1, 1, 0, 0])

In [ ]:
# np.argmin
# smallest value of the indices
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
np.argmin(a)

np.int64(7)

In [ ]:
# np.cumsum
# add karta hai values .....
# just likes 74+91 = 165, 165+59 = 224
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
np.cumsum(a)

array([ 56, 142, 223, 322, 343, 431, 482, 490, 585, 637, 714, 763, 790,
       888, 896])

In [ ]:
b

array([[22, 24, 70, 17],
       [92, 23, 42,  3],
       [10, 81,  1, 19],
       [11, 91,  1, 11],
       [78, 24,  4, 33],
       [71, 51, 34, 50]])

In [ ]:
np.cumsum(b)

array([ 22,  46, 116, 133, 225, 248, 290, 293, 303, 384, 385, 404, 415,
       506, 507, 518, 596, 620, 624, 657, 728, 779, 813, 863])

In [ ]:
np.cumsum(b,axis=1)
# row

array([[ 22,  46, 116, 133],
       [ 92, 115, 157, 160],
       [ 10,  91,  92, 111],
       [ 11, 102, 103, 114],
       [ 78, 102, 106, 139],
       [ 71, 122, 156, 206]])

In [ ]:
np.cumsum(b,axis=0)
# column

array([[ 22,  24,  70,  17],
       [114,  47, 112,  20],
       [124, 128, 113,  39],
       [135, 219, 114,  50],
       [213, 243, 118,  83],
       [284, 294, 152, 133]])

In [ ]:
# np.cumprod
# multiple the values
# 74*91 = 6734
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
np.cumprod(a)

array([                  56,                 4816,               390096,
                   38619504,            811009584,          71368843392,
              3639811012992,       29118488103936,     2766256369873920,
         143845331233443840, -7370653568734375936,  7772856606206611456,
        6952943556773441536, -1141062163456139264, -9128497307649114112])

In [ ]:
# np.percentile
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
np.percentile(a,0)

np.float64(8.0)

In [ ]:
np.percentile(a,100)

np.float64(99.0)

In [ ]:
np.percentile(a,50)

np.float64(56.0)

In [ ]:
# np.histogram
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 0, 2, 0, 1, 3, 0, 1, 3, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
# np.corrcoef
# return pearson product-moment correlation coefficients
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [ ]:
# np.isin
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
a[np.isin(a,items)]

array([], dtype=int64)

In [ ]:
# np.flip
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
np.flip(a)

array([ 8, 98, 27, 49, 77, 52, 95,  8, 51, 88, 21, 99, 81, 86, 56])

In [ ]:
b

array([[22, 24, 70, 17],
       [92, 23, 42,  3],
       [10, 81,  1, 19],
       [11, 91,  1, 11],
       [78, 24,  4, 33],
       [71, 51, 34, 50]])

In [ ]:
np.flip(b)

array([[50, 34, 51, 71],
       [33,  4, 24, 78],
       [11,  1, 91, 11],
       [19,  1, 81, 10],
       [ 3, 42, 23, 92],
       [17, 70, 24, 22]])

In [ ]:
np.flip(b,axis=0)

array([[71, 51, 34, 50],
       [78, 24,  4, 33],
       [11, 91,  1, 11],
       [10, 81,  1, 19],
       [92, 23, 42,  3],
       [22, 24, 70, 17]])

In [ ]:
np.flip(b,axis=1)

array([[17, 70, 24, 22],
       [ 3, 42, 23, 92],
       [19,  1, 81, 10],
       [11,  1, 91, 11],
       [33,  4, 24, 78],
       [50, 34, 51, 71]])

In [ ]:
# np.put
a

array([56, 86, 81, 99, 21, 88, 51,  8, 95, 52, 77, 49, 27, 98,  8])

In [ ]:
np.put(a,[0,1],[110,530])

In [ ]:
# np.delete
a

array([110, 530,  81,  99,  21,  88,  51,   8,  95,  52,  77,  49,  27,
        98,   8])

In [ ]:
np.delete(a,0)

array([530,  81,  99,  21,  88,  51,   8,  95,  52,  77,  49,  27,  98,
         8])

In [ ]:
np.delete(a,[0,2,4])

array([530,  99,  88,  51,   8,  95,  52,  77,  49,  27,  98,   8])

In [ ]:
# set functions
# 1 np.union1d
# 2 np.intersect1d
# 3 np.setdiff1d
# 4 np.setxor1d
# 5 np.in1d

m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
np.in1d(m,1)

/tmp/ipython-input-77-3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

In [ ]:
np.in1d(m,10)

/tmp/ipython-input-78-3337556509.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,10)


array([False, False, False, False, False])

In [ ]:
n[np.in1d(m,1)]

/tmp/ipython-input-80-490781921.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  n[np.in1d(m,1)]


array([3])

In [ ]:
# np.clip
a

array([110, 530,  81,  99,  21,  88,  51,   8,  95,  52,  77,  49,  27,
        98,   8])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 25, 75, 51, 25, 75, 52, 75, 49, 27, 75, 25])