<a href="https://colab.research.google.com/github/gudiya-archi/Data-science/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy array vs python lists

# speed
# list

a = [i for i in range (10000000)]
b = [i for i in range (10000000,20000000)]
c = []
import time

start = time.time()
for i in range (len(a)):
  c.append(a[i]+b[i])
print(time.time()-start)

2.394333600997925


In [ ]:
# Numpy
import numpy as np
a = [i for i in range (10000000)]
b = [i for i in range (10000000,20000000)]

start = time.time()
c = a + b
print(time.time()-start)

0.3656604290008545


In [ ]:
2.56/0.38

6.7368421052631575

In [ ]:
# memory
a = [i for i in range (10000000)]
import sys
sys.getsizeof(a)

89095160

In [ ]:
a = np.arange(10000000)
sys.getsizeof(a)


80000112

In [ ]:
a = np.arange(10000000,dtype=np.int32)
sys.getsizeof(a)


40000112

In [ ]:
a = np.arange(10000000,dtype=np.int16)
sys.getsizeof(a)


20000112

In [ ]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)


10000112

In [ ]:
# Advanced Indexing

# Normal Indexing and slicing
import numpy as np
a = np.arange(12).reshape(4,3)
a


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a[1,2]

np.int64(5)

In [ ]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [ ]:
# Fancy Indexing
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a[::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [ ]:
a[[0,2,3,]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# Advanced Indexing

# Normal Indexing and slicing
import numpy as np
a = np.arange(24).reshape(6,4)
a



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [ ]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
# Boolean Indexing
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[93,  8, 30, 77],
       [46, 57, 49, 55],
       [68, 63,  3,  3],
       [70, 30, 18, 69],
       [97, 57, 76, 50],
       [90, 20, 40, 41]])

In [ ]:
# find all number greater than 50
a > 50

array([[ True, False, False,  True],
       [False,  True, False,  True],
       [ True,  True, False, False],
       [ True, False, False,  True],
       [ True,  True,  True, False],
       [ True, False, False, False]])

In [ ]:
a [a > 50]

array([93, 77, 57, 55, 68, 63, 70, 69, 97, 57, 76, 90])

In [ ]:
# find out even numbers
a % 2 == 0

array([[False,  True,  True, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True,  True,  True, False],
       [False, False,  True,  True],
       [ True,  True,  True, False]])

In [ ]:
a [a % 2 == 0]

array([ 8, 30, 46, 68, 70, 30, 18, 76, 50, 90, 20, 40])

In [ ]:
# find all numbers greater than 50 and are even
(a > 50) & (a % 2 == 0)

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False,  True, False],
       [ True, False, False, False]])

In [ ]:
a [(a > 50) & (a % 2 == 0)]

array([68, 70, 76, 90])

In [ ]:
# find all numbers divisible by 7
a[a % 7 == 0]

array([77, 49, 63, 70])

In [ ]:
# find all numbers  not divisible by 7
a[~(a % 7 == 0)]

array([93,  8, 30, 46, 57, 55, 68,  3,  3, 30, 18, 69, 97, 57, 76, 50, 90,
       20, 40, 41])

In [ ]:
#   --> Broadcasting <--

# same shape
import numpy as np
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print (a)
print (b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [ ]:
#   --> Broadcasting <--

# diff shape
import numpy as np
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print (a)
print (b)



[[0 1 2]
 [3 4 5]]
[[0 1 2]]


In [ ]:
print(a+ b)

[[0 2 4]
 [3 5 7]]


In [ ]:
#   --> Broadcasting <--

# more examples
import numpy as np
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print (a)
print (b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:

import numpy as np
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print (a)
print (b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


In [ ]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:

import numpy as np
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print (a)
print (b)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [ ]:
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
import numpy as np
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]


In [ ]:
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
import numpy as np
a = np.array([1])
# shape -> (1,1)

b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

[1]
[[0 1]
 [2 3]]


In [ ]:
print(a+b)

[[1 2]
 [3 4]]


In [ ]:
import numpy as np
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
import numpy as np
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


In [ ]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 